package proyectofinal;

import java.awt.Color;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author victo
 */
public class Registrarse extends javax.swing.JFrame  {

public Registrarse() {
    initComponents();
    this.setLocationRelativeTo(null);


    javax.swing.SwingUtilities.invokeLater(() -> {
        ajustarImagen();
    });
}

private void ajustarImagen() {
    ImageIcon icon = new ImageIcon(getClass().getResource("/Imagenes/Inicio.png"));
    Image img = icon.getImage();

    Image imgEscalada = img.getScaledInstance(
        jLabel2.getWidth(),
        jLabel2.getHeight(),
        Image.SCALE_SMOOTH
    );

    jLabel2.setIcon(new ImageIcon(imgEscalada)); 
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new JPanelRedondeado();
        jPanel2 = new JPanelRedondeado();
        txtNombre = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jLabelApellido = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabelFechaNac = new javax.swing.JLabel();
        txtFechaNac = new javax.swing.JTextField();
        jLabelNacionalidad = new javax.swing.JLabel();
        txtNacionalidad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabelPasaporte = new javax.swing.JLabel();
        txtPasaporte = new javax.swing.JTextField();
        jLabelCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabelTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabelUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabelContra = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JPasswordField();
        btnRegistrar = new javax.swing.JButton();
        Cerrar = new javax.swing.JPanel();
        closeText = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMinimumSize(new java.awt.Dimension(650, 600));
        jPanel3.setPreferredSize(new java.awt.Dimension(650, 600));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.setMaximumSize(new java.awt.Dimension(290, 540));
        jPanel2.setMinimumSize(new java.awt.Dimension(290, 540));
        jPanel2.setPreferredSize(new java.awt.Dimension(290, 540));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombre.setText(" Ingrese");
        txtNombre.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreMouseClicked(evt);
            }
        });
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 130, 25));

        jLabelNombre.setText("Nombre:");
        jPanel2.add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, 25));

        jLabelApellido.setText("Apellido:");
        jPanel2.add(jLabelApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 80, 25));

        txtApellido.setText("Ingrese");
        jPanel2.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 130, 25));

        jLabelFechaNac.setText("Fecha Nac.:");
        jPanel2.add(jLabelFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 100, 25));

        txtFechaNac.setText("yyyy-mm-dd");
        txtFechaNac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaNacActionPerformed(evt);
            }
        });
        jPanel2.add(txtFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 130, 25));

        jLabelNacionalidad.setText("Nacionalidad:");
        jPanel2.add(jLabelNacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 80, 25));

        txtNacionalidad.setText("Ingrese");
        jPanel2.add(txtNacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 130, 25));

        jLabel1.setText("  ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabelPasaporte.setText("Pasaporte:");
        jPanel2.add(jLabelPasaporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 80, 25));

        txtPasaporte.setText("Ingrese");
        txtPasaporte.setToolTipText("");
        txtPasaporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasaporteActionPerformed(evt);
            }
        });
        jPanel2.add(txtPasaporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 130, 25));

        jLabelCorreo.setText("Correo:");
        jPanel2.add(jLabelCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 80, 25));

        txtCorreo.setText("Ingrese");
        jPanel2.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 130, 25));

        jLabelTelefono.setText("Telefono:");
        jPanel2.add(jLabelTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 80, 25));

        txtTelefono.setText("Ingrese");
        jPanel2.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 130, 25));

        jLabelUsuario.setText("Usuario");
        jPanel2.add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 80, 25));

        txtUsuario.setText("Ingrese");
        jPanel2.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 130, 25));

        jLabelContra.setText("Contraseña:");
        jPanel2.add(jLabelContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        txtContrasena.setText("***********");
        txtContrasena.setCaretPosition(7);
        jPanel2.add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 130, 30));

        btnRegistrar.setText("Registrarse");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, -1, -1));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 290, 360));

        Cerrar.setBackground(new java.awt.Color(172, 101, 39));
        Cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CerrarMouseExited(evt);
            }
        });
        Cerrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        closeText.setText("x");
        Cerrar.add(closeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanel3.add(Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 30, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Inicio.jpg"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarMouseEntered
        // TODO add your handling code here:
        Cerrar.setBackground(Color.red);
        closeText.setForeground(Color.WHITE);
        
    }//GEN-LAST:event_CerrarMouseEntered

    private void CerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarMouseExited
        // TODO add your handling code here:
        Cerrar.setBackground(Color.decode("#AC6527"));
        closeText.setForeground(Color.BLACK);
    }//GEN-LAST:event_CerrarMouseExited

    private void CerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_CerrarMouseClicked

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMouseClicked
        // TODO add your handling code here:
        txtNombre.setText("");
        txtNombre.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtNombreMouseClicked

    private void txtFechaNacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaNacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaNacActionPerformed

    private void txtPasaporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasaporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasaporteActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

    String nombre = txtNombre.getText().trim();
    String apellido = txtApellido.getText().trim();
    String usuario = txtUsuario.getText().trim();   
    String fechaNac = txtFechaNac.getText().trim();
    String nacionalidad = txtNacionalidad.getText().trim();
    String pasaporte = txtPasaporte.getText().trim();
    String correo = txtCorreo.getText().trim();
    String telefono = txtTelefono.getText().trim();
    String contrasena = new String(txtContrasena.getPassword()).trim();


    if (nombre.isEmpty() || apellido.isEmpty() || usuario.isEmpty() || fechaNac.isEmpty() ||
        nacionalidad.isEmpty() || pasaporte.isEmpty() || correo.isEmpty() ||
        telefono.isEmpty() || contrasena.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios");
        return;
    }

    try {
        java.sql.Date.valueOf(fechaNac);
    } catch (IllegalArgumentException e) {
        JOptionPane.showMessageDialog(this, "Fecha invalida. Use formato yyyy-MM-dd (ej. 2000-01-01)");
        return;
    }

    String sql = "INSERT INTO usuario (nombre, apellido, usuario, fechaDeNacimiento, nacionalidad, pasaporte, correo, telefono, contraseña) VALUES (?,?,?,?,?,?,?,?,?)";
    try (Connection conn = ConexionBD.getConnection();
         PreparedStatement pstmt = conn.prepareStatement(sql)) {
        pstmt.setString(1, nombre);
        pstmt.setString(2, apellido);
        pstmt.setString(3, usuario);
        pstmt.setDate(4, java.sql.Date.valueOf(fechaNac));
        pstmt.setString(5, nacionalidad);
        pstmt.setString(6, pasaporte);
        pstmt.setString(7, correo);
        pstmt.setString(8, telefono);
        pstmt.setString(9, contrasena);

        int filas = pstmt.executeUpdate();
        if (filas > 0) {
            JOptionPane.showMessageDialog(this, "Registro exitoso. Ahora inicia sesion con tu usuario.");
            new InicioSesion().setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Error al registrar");
        }
    } catch (SQLException e) {
        e.printStackTrace();
        if (e.getErrorCode() == 1062) {
      
            JOptionPane.showMessageDialog(this, "El usuario, correo o pasaporte ya esta registrado. Usa otros datos.");
        } else {
            JOptionPane.showMessageDialog(this, "Error de base de datos: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cerrar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel closeText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelContra;
    private javax.swing.JLabel jLabelCorreo;
    private javax.swing.JLabel jLabelFechaNac;
    private javax.swing.JLabel jLabelNacionalidad;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPasaporte;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtFechaNac;
    private javax.swing.JTextField txtNacionalidad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPasaporte;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
