package proyectofinal;

import javax.swing.ImageIcon;
import java.awt.Image;
import proyectofinal.navegacion.PanelAdministrador;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import proyectofinal.navegacion.PaginaPrincipalUsuario;

/**
 *
 * @author victo
 */
public class InicioSesion extends javax.swing.JFrame {

    public InicioSesion() {
        initComponents();
        this.setLocationRelativeTo(null);
        javax.swing.SwingUtilities.invokeLater(() -> {
            ajustarImagen();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new JPanelRedondeado();
        jPanel2 = new JPanelRedondeado();
        Contra = new javax.swing.JPasswordField();
        Usuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        BotonInicarSesion = new JPanelRedondeado();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        Cerrar = new javax.swing.JPanel();
        closeText = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMaximumSize(new java.awt.Dimension(650, 600));
        jPanel3.setMinimumSize(new java.awt.Dimension(650, 600));
        jPanel3.setPreferredSize(new java.awt.Dimension(650, 600));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(290, 540));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Contra.setFont(new java.awt.Font("Corbel Light", 0, 12)); // NOI18N
        Contra.setForeground(new java.awt.Color(204, 204, 204));
        Contra.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Contra.setText("Ingrese");
        Contra.setBorder(null);
        Contra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ContraMouseClicked(evt);
            }
        });
        jPanel2.add(Contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 210, 20));

        Usuario.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        Usuario.setForeground(new java.awt.Color(204, 204, 204));
        Usuario.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Usuario.setText("Ingrese");
        Usuario.setBorder(null);
        Usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UsuarioMouseClicked(evt);
            }
        });
        jPanel2.add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 210, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 210, 10));

        BotonInicarSesion.setBackground(new java.awt.Color(172, 101, 39));
        BotonInicarSesion.setToolTipText("Hola");
        BotonInicarSesion.setFont(new java.awt.Font("Corbel Light", 0, 12)); // NOI18N
        BotonInicarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonInicarSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonInicarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonInicarSesionMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Iniciar Sesión");

        javax.swing.GroupLayout BotonInicarSesionLayout = new javax.swing.GroupLayout(BotonInicarSesion);
        BotonInicarSesion.setLayout(BotonInicarSesionLayout);
        BotonInicarSesionLayout.setHorizontalGroup(
            BotonInicarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonInicarSesionLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(55, 55, 55))
        );
        BotonInicarSesionLayout.setVerticalGroup(
            BotonInicarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(BotonInicarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 210, 40));

        jLabel8.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 255));
        jLabel8.setText("REGISTRATE");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 120, -1));

        jLabel9.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        jLabel9.setText("Usuario");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 130, 30));

        jLabel10.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        jLabel10.setText("Contraseña");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));

        jLabel11.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        jLabel11.setText("¿Aún no tienes una cuenta?");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 210, 10));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo blanco peque.jpg"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 120, 80));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 290, 370));

        Cerrar.setBackground(new java.awt.Color(172, 101, 39));
        Cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CerrarMouseExited(evt);
            }
        });
        Cerrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        closeText.setText("x");
        Cerrar.add(closeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanel3.add(Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 30, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Inicio.png"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(1000, 800));
        jLabel2.setMinimumSize(new java.awt.Dimension(1000, 800));
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 410));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void ajustarImagen() {
        java.net.URL rutaImagen = getClass().getResource("/Imagenes/Inicio.png");

        if (rutaImagen != null) {
            ImageIcon icon = new ImageIcon(rutaImagen);

            Image img = icon.getImage();

            Image imgEscalada = img.getScaledInstance(
                    jLabel2.getWidth(),
                    jLabel2.getHeight(),
                    Image.SCALE_SMOOTH
            );

            jLabel2.setIcon(new ImageIcon(imgEscalada));
        } else {
            System.out.println("ERROR: No se encontro la imagen en /Imagenes/Inicio.jpg");
        }
        //
    }
    private void ContraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContraMouseClicked
        // TODO add your handling code here:
        Contra.setText("");
        Contra.setForeground(Color.BLACK);
    }//GEN-LAST:event_ContraMouseClicked

    private void UsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsuarioMouseClicked
        // TODO add your handling code here:
        Usuario.setText("");
        Usuario.setForeground(Color.BLACK);
    }//GEN-LAST:event_UsuarioMouseClicked

    private void BotonInicarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonInicarSesionMouseEntered
        // TODO add your handling code here:
        BotonInicarSesion.setBackground(Color.decode("#CB8B44"));
    }//GEN-LAST:event_BotonInicarSesionMouseEntered

    private void BotonInicarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonInicarSesionMouseExited
        // TODO add your handling code here:
        BotonInicarSesion.setBackground(Color.decode("#AC6527"));
    }//GEN-LAST:event_BotonInicarSesionMouseExited

    private void CerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarMouseEntered
        // TODO add your handling code here:
        Cerrar.setBackground(Color.red);
        closeText.setForeground(Color.WHITE);

    }//GEN-LAST:event_CerrarMouseEntered

    private void CerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarMouseExited
        // TODO add your handling code here:
        Cerrar.setBackground(Color.decode("a727bd"));
        closeText.setForeground(Color.BLACK);
    }//GEN-LAST:event_CerrarMouseExited

    private void CerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_CerrarMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        Registrarse nuevoUsuario = new Registrarse();
        nuevoUsuario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void BotonInicarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonInicarSesionMouseClicked
        String usuarioLogin = Usuario.getText().trim();
        String contrasena = new String(Contra.getPassword()).trim();

        if (usuarioLogin.isEmpty() || contrasena.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Escribe tu usuario y contraseña");
            return;
        }

        try (Connection conn = ConexionBD.getConnection()) {

            if (usuarioLogin.startsWith("admin")) {
                String sqlAdmin = "SELECT nombre, apellido FROM empleado WHERE usuario = ? AND contraseña = ?";
                try (PreparedStatement pstmt = conn.prepareStatement(sqlAdmin)) {
                    pstmt.setString(1, usuarioLogin);
                    pstmt.setString(2, contrasena);
                    try (ResultSet rs = pstmt.executeQuery()) {
                        if (rs.next()) {
                            String nombreAdmin = rs.getString("nombre") + " " + rs.getString("apellido");
                            new PanelAdministrador(nombreAdmin).setVisible(true);
                            this.dispose();
                        } else {
                            JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos");
                        }
                    }
                }

            } else {
                String sqlUser = "SELECT id_usuario, nombre, apellido FROM usuario WHERE usuario = ? AND contraseña = ?";
                try (PreparedStatement pstmt = conn.prepareStatement(sqlUser)) {
                    pstmt.setString(1, usuarioLogin);
                    pstmt.setString(2, contrasena);
                    try (ResultSet rs = pstmt.executeQuery()) {
                        if (rs.next()) {
                            int idUsuario = rs.getInt("id_usuario");
                            String nombreUser = rs.getString("nombre") + " " + rs.getString("apellido");
                            new proyectofinal.navegacion.SeleccionViajePasajero(nombreUser, idUsuario).setVisible(true);
                            this.dispose();
                        } else {
                            JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos");
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
                    }
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al conectar con la base de datos");
        }

    }//GEN-LAST:event_BotonInicarSesionMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BotonInicarSesion;
    private javax.swing.JPanel Cerrar;
    private javax.swing.JPasswordField Contra;
    private javax.swing.JTextField Usuario;
    private javax.swing.JLabel closeText;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
