package proyectofinal;

import java.awt.Color;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author victo
 */
public class Registrarse extends javax.swing.JFrame  {

public Registrarse() {
    initComponents();
    this.setLocationRelativeTo(null);


    javax.swing.SwingUtilities.invokeLater(() -> {
        ajustarImagen();
    });
}

private void ajustarImagen() {
        ImageIcon icon = new ImageIcon(getClass().getResource("/Imagenes/Inicio.jpg"));
        Image imgOriginal = icon.getImage();
        int ancho = icon.getIconWidth();
        int alto = icon.getIconHeight();

        java.awt.image.BufferedImage imgRotada = new java.awt.image.BufferedImage(alto, ancho, java.awt.image.BufferedImage.TYPE_INT_ARGB);
        java.awt.Graphics2D g2d = imgRotada.createGraphics();
        g2d.translate(alto, 0);
        g2d.rotate(Math.toRadians(90));
        g2d.drawImage(imgOriginal, 0, 0, null);
        g2d.dispose();

        Image imgEscalada = imgRotada.getScaledInstance(
            620, 
            410, 
            Image.SCALE_SMOOTH
        );

        jLabel2.setIcon(new ImageIcon(imgEscalada)); 
        jLabel2.setSize(620, 410);
    }
private void ajustarLogo() {
        ImageIcon iconLogo = new ImageIcon(getClass().getResource("/Imagenes/logo2.jpg"));
        Image img = iconLogo.getImage();

        Image logoEscalado = img.getScaledInstance(150, 100, Image.SCALE_SMOOTH);

        jLabel4.setIcon(new ImageIcon(logoEscalado));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new JPanelRedondeado();
        jPanel2 = new JPanelRedondeado();
        txtNombre = new javax.swing.JTextField();
        jLabelApellido = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabelFechaNac = new javax.swing.JLabel();
        txtFechaNac = new javax.swing.JTextField();
        jLabelNacionalidad = new javax.swing.JLabel();
        txtNacionalidad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabelPasaporte = new javax.swing.JLabel();
        txtPasaporte = new javax.swing.JTextField();
        jLabelCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabelTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabelUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabelContra = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JPasswordField();
        btnRegistrar = new javax.swing.JButton();
        jLabelNombre = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelFechaNac1 = new javax.swing.JLabel();
        Cerrar = new javax.swing.JPanel();
        closeText = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMinimumSize(new java.awt.Dimension(650, 600));
        jPanel3.setPreferredSize(new java.awt.Dimension(650, 600));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(290, 540));
        jPanel2.setMinimumSize(new java.awt.Dimension(290, 540));
        jPanel2.setPreferredSize(new java.awt.Dimension(290, 540));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombre.setFont(new java.awt.Font("Corbel Light", 0, 14)); // NOI18N
        txtNombre.setText(" Ingrese");
        txtNombre.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(129, 39, 189)));
        txtNombre.setCaretColor(new java.awt.Color(153, 153, 153));
        txtNombre.setMinimumSize(new java.awt.Dimension(64, 24));
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreMouseClicked(evt);
            }
        });
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 100, 30));

        jLabelApellido.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabelApellido.setForeground(new java.awt.Color(117, 36, 165));
        jLabelApellido.setText("Apellido:");
        jPanel2.add(jLabelApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 80, 25));

        txtApellido.setFont(new java.awt.Font("Corbel Light", 0, 14)); // NOI18N
        txtApellido.setText("Ingrese");
        txtApellido.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(129, 39, 189)));
        jPanel2.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 90, 25));

        jLabelFechaNac.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabelFechaNac.setForeground(new java.awt.Color(117, 36, 165));
        jLabelFechaNac.setText("Nacimiento:");
        jPanel2.add(jLabelFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 110, 25));

        txtFechaNac.setFont(new java.awt.Font("Corbel Light", 0, 14)); // NOI18N
        txtFechaNac.setText("yyyy-mm-dd");
        txtFechaNac.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(129, 39, 189)));
        jPanel2.add(txtFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 100, 25));

        jLabelNacionalidad.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabelNacionalidad.setForeground(new java.awt.Color(117, 36, 165));
        jLabelNacionalidad.setText("Nacionalidad:");
        jPanel2.add(jLabelNacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 120, 25));

        txtNacionalidad.setFont(new java.awt.Font("Corbel Light", 0, 14)); // NOI18N
        txtNacionalidad.setText("Ingrese");
        txtNacionalidad.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(129, 39, 189)));
        jPanel2.add(txtNacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 90, 25));

        jLabel1.setText("  ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jLabelPasaporte.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabelPasaporte.setForeground(new java.awt.Color(117, 36, 165));
        jLabelPasaporte.setText("Pasaporte:");
        jPanel2.add(jLabelPasaporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 100, 25));

        txtPasaporte.setFont(new java.awt.Font("Corbel Light", 0, 14)); // NOI18N
        txtPasaporte.setText("Ingrese");
        txtPasaporte.setToolTipText("");
        txtPasaporte.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(129, 39, 189)));
        txtPasaporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasaporteActionPerformed(evt);
            }
        });
        jPanel2.add(txtPasaporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 100, 25));

        jLabelCorreo.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabelCorreo.setForeground(new java.awt.Color(117, 36, 165));
        jLabelCorreo.setText("Correo:");
        jPanel2.add(jLabelCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, 25));

        txtCorreo.setFont(new java.awt.Font("Corbel Light", 0, 14)); // NOI18N
        txtCorreo.setText("ejemplo@gmail.com");
        txtCorreo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(129, 39, 189)));
        jPanel2.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 80, 25));

        jLabelTelefono.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabelTelefono.setForeground(new java.awt.Color(117, 36, 165));
        jLabelTelefono.setText("Telefono:");
        jPanel2.add(jLabelTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 100, 25));

        txtTelefono.setFont(new java.awt.Font("Corbel Light", 0, 14)); // NOI18N
        txtTelefono.setText("Ingrese");
        txtTelefono.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(129, 39, 189)));
        jPanel2.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 100, 25));

        jLabelUsuario.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(117, 36, 165));
        jLabelUsuario.setText("Usuario:");
        jPanel2.add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, -1, 25));

        txtUsuario.setFont(new java.awt.Font("Corbel Light", 0, 14)); // NOI18N
        txtUsuario.setText("Ingrese");
        txtUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(129, 39, 189)));
        jPanel2.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 90, 25));

        jLabelContra.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabelContra.setForeground(new java.awt.Color(117, 36, 165));
        jLabelContra.setText("Contraseña:");
        jPanel2.add(jLabelContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));

        txtContrasena.setFont(new java.awt.Font("Corbel Light", 0, 14)); // NOI18N
        txtContrasena.setForeground(new java.awt.Color(204, 204, 204));
        txtContrasena.setText("***********");
        txtContrasena.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(129, 39, 189)));
        jPanel2.add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 130, 30));

        btnRegistrar.setBackground(new java.awt.Color(117, 36, 165));
        btnRegistrar.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrarse");
        btnRegistrar.setBorder(null);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 90, 30));

        jLabelNombre.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(117, 36, 165));
        jLabelNombre.setText("Nombre:");
        jPanel2.add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 80, 25));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo blanco def ahora si.jpg"))); // NOI18N
        jLabel4.setMaximumSize(new java.awt.Dimension(200, 200));
        jLabel4.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 110));

        jLabelFechaNac1.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabelFechaNac1.setForeground(new java.awt.Color(117, 36, 165));
        jLabelFechaNac1.setText("Fecha de");
        jPanel2.add(jLabelFechaNac1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 110, 25));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 530, 380));

        Cerrar.setBackground(new java.awt.Color(255, 255, 255));
        Cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CerrarMouseExited(evt);
            }
        });
        Cerrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        closeText.setText("x");
        Cerrar.add(closeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanel3.add(Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 30, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Inicio.jpg"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarMouseEntered
        Cerrar.setBackground(Color.red);
        closeText.setForeground(Color.WHITE);
        
    }//GEN-LAST:event_CerrarMouseEntered

    private void CerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarMouseExited
        Cerrar.setBackground(Color.WHITE);
        closeText.setForeground(Color.BLACK);
    }//GEN-LAST:event_CerrarMouseExited

    private void CerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarMouseClicked
        this.dispose();
    }//GEN-LAST:event_CerrarMouseClicked

    private void txtNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMouseClicked
        // TODO add your handling code here:
        txtNombre.setText("");
        txtNombre.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtNombreMouseClicked

    private void txtPasaporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasaporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasaporteActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
                                          
        String nombre = txtNombre.getText().trim();
        String apellido = txtApellido.getText().trim();
        String usuario = txtUsuario.getText().trim();   
        String fechaNac = txtFechaNac.getText().trim();
        String nacionalidad = txtNacionalidad.getText().trim();
        String pasaporte = txtPasaporte.getText().trim();
        String correo = txtCorreo.getText().trim();
        String telefono = txtTelefono.getText().trim();
        String contrasena = new String(txtContrasena.getPassword()).trim();

        if (nombre.isEmpty() || apellido.isEmpty() || usuario.isEmpty() || fechaNac.isEmpty() ||
            nacionalidad.isEmpty() || pasaporte.isEmpty() || correo.isEmpty() ||
            telefono.isEmpty() || contrasena.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios");
            return;
        }

        try {
            java.sql.Date.valueOf(fechaNac);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, "Fecha invalida. Use formato yyyy-MM-dd (ej. 2000-01-01)");
            return;
        }

        String sql = "INSERT INTO usuario (nombre, apellido, usuario, fechaDeNacimiento, nacionalidad, pasaporte, correo, telefono, contraseña) VALUES (?,?,?,?,?,?,?,?,?)";
        try (Connection conn = ConexionBD.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setString(1, nombre);
            pstmt.setString(2, apellido);
            pstmt.setString(3, usuario);
            pstmt.setDate(4, java.sql.Date.valueOf(fechaNac));
            pstmt.setString(5, nacionalidad);
            pstmt.setString(6, pasaporte);
            pstmt.setString(7, correo);
            pstmt.setString(8, telefono);
            pstmt.setString(9, contrasena);

            int filas = pstmt.executeUpdate();
            if (filas > 0) {
                JOptionPane.showMessageDialog(this, "Registro exitoso. Ahora inicia sesion con tu usuario.");
                new InicioSesion().setVisible(true); 
                this.dispose(); 
            } else {
                JOptionPane.showMessageDialog(this, "Error al registrar");
            }
        } catch (SQLException e) {
            if (e.getErrorCode() == 1062) {
                JOptionPane.showMessageDialog(this, "El usuario, correo o pasaporte ya esta registrado. Usa otros datos.");
            } else {
                JOptionPane.showMessageDialog(this, "Error de base de datos: " + e.getMessage());
            }
        }
    
    }//GEN-LAST:event_btnRegistrarActionPerformed

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cerrar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel closeText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelContra;
    private javax.swing.JLabel jLabelCorreo;
    private javax.swing.JLabel jLabelFechaNac;
    private javax.swing.JLabel jLabelFechaNac1;
    private javax.swing.JLabel jLabelNacionalidad;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPasaporte;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtFechaNac;
    private javax.swing.JTextField txtNacionalidad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPasaporte;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
