package proyectofinal;

import java.awt.Color;

/**
 *
 * @author 186377
 */
public class RegristrarAdmin extends javax.swing.JFrame {

    /**
     * Creates new form RegristrarAdmin
     */
    public RegristrarAdmin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 =  new proyectofinal.JPanelRedondeado();
        txtNombre = new javax.swing.JLabel();
        txtApellido = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JLabel();
        txtGenero = new javax.swing.JLabel();
        txtFecha = new javax.swing.JLabel();
        txtRFC = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JLabel();
        txtCorreoField = new javax.swing.JTextField();
        NombreField = new javax.swing.JTextField();
        CodigoField = new javax.swing.JTextField();
        apellidoField = new javax.swing.JTextField();
        ApellidoField = new javax.swing.JTextField();
        txtFechaField = new javax.swing.JTextField();
        txtTelefonoField = new javax.swing.JTextField();
        txtRFCField = new javax.swing.JTextField();
        FtxtContrasenaField = new javax.swing.JPasswordField();
        btnRegistrarAdmin = new javax.swing.JButton();
        cbxGenero = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Cerrar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(51, 0, 51));
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(204, 0, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        jPanel1.setMaximumSize(new java.awt.Dimension(690, 325));
        jPanel1.setLayout(null);

        txtNombre.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(117, 36, 165));
        txtNombre.setText("Nombre:");
        jPanel1.add(txtNombre);
        txtNombre.setBounds(80, 130, 75, 25);

        txtApellido.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(117, 36, 165));
        txtApellido.setText("Apellido:");
        jPanel1.add(txtApellido);
        txtApellido.setBounds(80, 170, 77, 25);

        txtUsuario.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(117, 36, 165));
        txtUsuario.setText("Usuario:");
        jPanel1.add(txtUsuario);
        txtUsuario.setBounds(80, 210, 71, 25);

        txtCodigo.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        txtCodigo.setForeground(new java.awt.Color(117, 36, 165));
        txtCodigo.setText("C. de empeado:");
        jPanel1.add(txtCodigo);
        txtCodigo.setBounds(40, 250, 132, 25);

        txtCorreo.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(117, 36, 165));
        txtCorreo.setText("Correo:");
        jPanel1.add(txtCorreo);
        txtCorreo.setBounds(80, 290, 63, 25);

        txtGenero.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        txtGenero.setForeground(new java.awt.Color(117, 36, 165));
        txtGenero.setText("Género:");
        jPanel1.add(txtGenero);
        txtGenero.setBounds(330, 300, 67, 25);

        txtFecha.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        txtFecha.setForeground(new java.awt.Color(117, 36, 165));
        txtFecha.setText("F. de Contratación:");
        jPanel1.add(txtFecha);
        txtFecha.setBounds(310, 250, 161, 25);

        txtRFC.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        txtRFC.setForeground(new java.awt.Color(117, 36, 165));
        txtRFC.setText("RFC:");
        jPanel1.add(txtRFC);
        txtRFC.setBounds(330, 210, 37, 25);

        txtContrasena.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        txtContrasena.setForeground(new java.awt.Color(117, 36, 165));
        txtContrasena.setText("Contraseña:");
        jPanel1.add(txtContrasena);
        txtContrasena.setBounds(330, 170, 101, 25);

        txtTelefono.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(117, 36, 165));
        txtTelefono.setText("Telefono:");
        jPanel1.add(txtTelefono);
        txtTelefono.setBounds(330, 130, 81, 25);

        txtCorreoField.setFont(new java.awt.Font("Leelawadee UI", 2, 14)); // NOI18N
        txtCorreoField.setForeground(new java.awt.Color(153, 153, 153));
        txtCorreoField.setText("Ingrese");
        txtCorreoField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtCorreoField);
        txtCorreoField.setBounds(180, 290, 95, 22);

        NombreField.setFont(new java.awt.Font("Leelawadee UI", 2, 14)); // NOI18N
        NombreField.setForeground(new java.awt.Color(153, 153, 153));
        NombreField.setText("Ingrese");
        NombreField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(NombreField);
        NombreField.setBounds(180, 130, 95, 22);

        CodigoField.setFont(new java.awt.Font("Leelawadee UI", 2, 14)); // NOI18N
        CodigoField.setForeground(new java.awt.Color(153, 153, 153));
        CodigoField.setText("Ingrese");
        CodigoField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(CodigoField);
        CodigoField.setBounds(180, 250, 95, 22);

        apellidoField.setFont(new java.awt.Font("Leelawadee UI", 2, 14)); // NOI18N
        apellidoField.setForeground(new java.awt.Color(153, 153, 153));
        apellidoField.setText("Ingrese");
        apellidoField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(apellidoField);
        apellidoField.setBounds(180, 210, 95, 22);

        ApellidoField.setFont(new java.awt.Font("Leelawadee UI", 2, 14)); // NOI18N
        ApellidoField.setForeground(new java.awt.Color(153, 153, 153));
        ApellidoField.setText("Ingrese");
        ApellidoField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(ApellidoField);
        ApellidoField.setBounds(180, 170, 95, 22);

        txtFechaField.setFont(new java.awt.Font("Leelawadee UI", 2, 14)); // NOI18N
        txtFechaField.setForeground(new java.awt.Color(153, 153, 153));
        txtFechaField.setText("yyyy-mm-dd");
        txtFechaField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtFechaField);
        txtFechaField.setBounds(480, 250, 100, 22);

        txtTelefonoField.setFont(new java.awt.Font("Leelawadee UI", 2, 14)); // NOI18N
        txtTelefonoField.setForeground(new java.awt.Color(153, 153, 153));
        txtTelefonoField.setText("Ingrese");
        txtTelefonoField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtTelefonoField);
        txtTelefonoField.setBounds(480, 130, 95, 22);

        txtRFCField.setFont(new java.awt.Font("Leelawadee UI", 2, 14)); // NOI18N
        txtRFCField.setForeground(new java.awt.Color(153, 153, 153));
        txtRFCField.setText("Ingrese");
        txtRFCField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtRFCField);
        txtRFCField.setBounds(480, 210, 100, 22);

        FtxtContrasenaField.setFont(new java.awt.Font("Leelawadee UI", 2, 14)); // NOI18N
        FtxtContrasenaField.setForeground(new java.awt.Color(153, 153, 153));
        FtxtContrasenaField.setText("jPasswordField1");
        FtxtContrasenaField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(FtxtContrasenaField);
        FtxtContrasenaField.setBounds(480, 170, 95, 22);

        btnRegistrarAdmin.setBackground(new java.awt.Color(0, 0, 0));
        btnRegistrarAdmin.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        btnRegistrarAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarAdmin.setText("Regristrar administrador");
        btnRegistrarAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarAdminActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarAdmin);
        btnRegistrarAdmin.setBounds(210, 350, 243, 32);

        cbxGenero.setFont(new java.awt.Font("Leelawadee UI", 2, 14)); // NOI18N
        cbxGenero.setForeground(new java.awt.Color(153, 153, 153));
        cbxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F", "M" }));
        cbxGenero.setBorder(null);
        jPanel1.add(cbxGenero);
        cbxGenero.setBounds(480, 300, 72, 24);

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(117, 36, 165));
        jLabel1.setText("ADMINISTRADORES");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 60, 500, 48);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo2miniii.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(490, 10, 160, 110);

        jLabel4.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(117, 36, 165));
        jLabel4.setText("ALTA DE");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(170, 20, 500, 41);

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 19, 659, 422));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicio.jpg"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, -1, -1));

        Cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CerrarMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("  X");

        javax.swing.GroupLayout CerrarLayout = new javax.swing.GroupLayout(Cerrar);
        Cerrar.setLayout(CerrarLayout);
        CerrarLayout.setHorizontalGroup(
            CerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CerrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        CerrarLayout.setVerticalGroup(
            CerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CerrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(696, Short.MAX_VALUE)
                .addComponent(Cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(428, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarAdminActionPerformed

        String nombre = NombreField.getText().trim();
        String apellido = ApellidoField.getText().trim();
        String usuario = apellidoField.getText().trim(); 
        String codigo = CodigoField.getText().trim();
        String correo = txtCorreoField.getText().trim();
        
        String telefono = txtTelefonoField.getText().trim();
        String rfc = txtRFCField.getText().trim();
        String fecha = txtFechaField.getText().trim(); 
        String contrasena = new String(FtxtContrasenaField.getPassword()).trim();
        String sexo = cbxGenero.getSelectedItem().toString(); 

        if(nombre.isEmpty() || apellido.isEmpty() || usuario.isEmpty() || codigo.isEmpty() || 
           correo.isEmpty() || telefono.isEmpty() || rfc.isEmpty() || fecha.isEmpty() || contrasena.isEmpty()) {
      
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, llena absolutamente todos los campos.");
            return; 
        }
        
        String sql = "INSERT INTO empleado (nombre, apellido, usuario, codigoEmpleado, correo, telefono, contraseña, sexo, rfc, fechaDeContratacion) VALUES (?,?,?,?,?,?,?,?,?,?)";
        try (java.sql.Connection con = proyectofinal.ConexionBD.getConnection();
             java.sql.PreparedStatement pst = con.prepareStatement(sql)) {

            pst.setString(1, nombre);
            pst.setString(2, apellido);
            pst.setString(3, usuario);
            pst.setString(4, codigo);
            pst.setString(5, correo);
            pst.setString(6, telefono);
            pst.setString(7, contrasena);
            pst.setString(8, sexo);
            pst.setString(9, rfc);

            pst.setDate(10, java.sql.Date.valueOf(fecha)); 
            pst.executeUpdate();
            
            javax.swing.JOptionPane.showMessageDialog(this, "Muy Bien! Nuevo administrador registrado");
            this.dispose(); 

        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar en BD: " + e.getMessage());
            
        } catch (IllegalArgumentException e) {
             javax.swing.JOptionPane.showMessageDialog(this, "Error: La fecha debe tener el formato YYYY-MM-DD (Ej. 2026-05-10)");
        }

    }//GEN-LAST:event_btnRegistrarAdminActionPerformed

    private void CerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarMouseClicked
        this.dispose();
    }//GEN-LAST:event_CerrarMouseClicked

    private void CerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarMouseEntered
        Cerrar.setBackground(Color.red);
        jLabel3.setForeground(Color.WHITE);
    }//GEN-LAST:event_CerrarMouseEntered

    private void CerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarMouseExited
        Cerrar.setBackground(Color.WHITE);
        jLabel3.setForeground(Color.BLACK);    }//GEN-LAST:event_CerrarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegristrarAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegristrarAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegristrarAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegristrarAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegristrarAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidoField;
    private javax.swing.JPanel Cerrar;
    private javax.swing.JTextField CodigoField;
    private javax.swing.JPasswordField FtxtContrasenaField;
    private javax.swing.JTextField NombreField;
    private javax.swing.JTextField apellidoField;
    private javax.swing.JButton btnRegistrarAdmin;
    private javax.swing.JComboBox<String> cbxGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel txtApellido;
    private javax.swing.JLabel txtCodigo;
    private javax.swing.JLabel txtContrasena;
    private javax.swing.JLabel txtCorreo;
    private javax.swing.JTextField txtCorreoField;
    private javax.swing.JLabel txtFecha;
    private javax.swing.JTextField txtFechaField;
    private javax.swing.JLabel txtGenero;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JLabel txtRFC;
    private javax.swing.JTextField txtRFCField;
    private javax.swing.JLabel txtTelefono;
    private javax.swing.JTextField txtTelefonoField;
    private javax.swing.JLabel txtUsuario;
    // End of variables declaration//GEN-END:variables
}
