/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectofinal.navegacion;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyectofinal.ConexionBD;
import proyectofinal.Vuelo;

public class SeleccionViajePasajero extends javax.swing.JFrame {
    
    private String nombreUsuario;
    private int idUsuario;

    // Constructor que recibe los datos de sesión
    public SeleccionViajePasajero(String nombreUsuario, int idUsuario) {
        initComponents();
        this.nombreUsuario = nombreUsuario;
        this.idUsuario = idUsuario;
        this.setLocationRelativeTo(null);
        cargarVuelos();
    }


    private void cargarVuelos() {
        DefaultTableModel modelo = (DefaultTableModel) tablaViajes.getModel();
        modelo.setRowCount(0);
        
        // Ajusta los JOIN según cómo llamaste a las tablas en tu base de datos
        String sql = "SELECT v.id_vuelo, c1.nombre AS origen, c2.nombre AS destino, v.numVuelo, v.horarioSalida, v.horarioLlegada, v.precioBoleto " +
                     "FROM vuelo v " +
                     "JOIN ciudad c1 ON v.id_origen = c1.id_ciudad " +
                     "JOIN ciudad c2 ON v.id_destino = c2.id_ciudad";
                     
        try (Connection con = ConexionBD.getConnection();
             Statement st = con.createStatement();
             ResultSet rs = st.executeQuery(sql)) {
             
             while (rs.next()) {
                 modelo.addRow(new Object[]{
                     rs.getInt("id_vuelo"),
                     rs.getString("origen"),
                     rs.getString("destino"),
                     rs.getString("numVuelo"),
                     rs.getString("horarioSalida"),
                     rs.getString("horarioLlegada"),
                     rs.getDouble("precioBoleto")
                 });
             }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar vuelos: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSiguiente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaViajes = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(217, 183, 240));

        btnSiguiente.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        tablaViajes.setBackground(new java.awt.Color(227, 227, 227));
        tablaViajes.setFont(new java.awt.Font("Corbel Light", 0, 12)); // NOI18N
        tablaViajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID ", "Ida", "Regreso", "No. de Vuelo", "Hora Salida", "Hora llegada", "Precio"
            }
        ));
        jScrollPane1.setViewportView(tablaViajes);

        jTextField1.setFont(new java.awt.Font("Corbel", 1, 36)); // NOI18N
        jTextField1.setText("Vuelos disponibles");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(btnSiguiente)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jTextField1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSiguiente)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
    int fila = tablaViajes.getSelectedRow();
        if (fila != -1) {
            // Extraemos los datos de la fila seleccionada en la tabla
            int id = (int) tablaViajes.getValueAt(fila, 0);
            String origen = tablaViajes.getValueAt(fila, 1).toString();
            String destino = tablaViajes.getValueAt(fila, 2).toString();
            String num = tablaViajes.getValueAt(fila, 3).toString();
            String sal = tablaViajes.getValueAt(fila, 4).toString();
            String lleg = tablaViajes.getValueAt(fila, 5).toString();
            double precio = Double.parseDouble(tablaViajes.getValueAt(fila, 6).toString());

            // Empaquetamos todo en el objeto
            Vuelo vueloElegido = new Vuelo(id, origen, destino, num, sal, lleg, precio);

            // Abrimos el avión enviando el usuario y el vuelo
            PaginaPrincipalUsuario ventanaAsientos = new PaginaPrincipalUsuario(nombreUsuario, vueloElegido);
            ventanaAsientos.setVisible(true);
            this.dispose();
            
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona un vuelo de la tabla para continuar.");
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tablaViajes;
    // End of variables declaration//GEN-END:variables
}
