package proyectofinal.navegacion;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.util.ArrayList; 
import proyectofinal.ConexionBD;

/**
 *
 * @author 186377
 */
public class FormularioParaVuelos extends javax.swing.JFrame {


    private int idVueloSeleccionado = 0; 
    private ArrayList<Integer> listaIdsCiudades = new ArrayList<>();

    public FormularioParaVuelos() {
        initComponents();
        cargarCiudades(); 
    }

  // recibe los datos desde ListaVuelos cuando presionamos "modificar
    public void cargarDatos(int id, String numV, int idO, int idD, String hSal, String hLleg, String fec, String est, int cap, double prec) {
        this.idVueloSeleccionado = id; 

        txtNumVuelo.setText(numV);
        txtHorarioSalida.setText(hSal);
        txtHorarioLlegada.setText(hLleg);
        txtFecha.setText(fec);
        txtEstado.setText(est);
        txtCapacidad.setText(String.valueOf(cap));
        txtPrecio.setText(String.valueOf(prec));
        
        // Selecciona la ciudad correcta en los ComboBox usando indexOf
        int indexOrigen = listaIdsCiudades.indexOf(idO);
        if(indexOrigen != -1) txtIdOrigen.setSelectedIndex(indexOrigen);
        
        int indexDestino = listaIdsCiudades.indexOf(idD);
        if(indexDestino != -1) txtIdDestino.setSelectedIndex(indexDestino);
    }


  void cargarCiudades() {
        String sql = "SELECT id_ciudad, nombre FROM ciudad";
        
        try (Connection conn = ConexionBD.getConnection(); 
             PreparedStatement pstmt = conn.prepareStatement(sql); 
             ResultSet rs = pstmt.executeQuery()) {

            txtIdOrigen.removeAllItems();
            txtIdDestino.removeAllItems();
            listaIdsCiudades.clear();

            while (rs.next()) {
                int idReal = rs.getInt("id_ciudad");
                String ciudad = rs.getString("nombre");
                
                listaIdsCiudades.add(idReal); // Guardamos el ID real 
                txtIdOrigen.addItem(ciudad);  
                txtIdDestino.addItem(ciudad);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar ciudades: " + e.getMessage());
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNumVuelo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtHorarioSalida = new javax.swing.JTextField();
        txtHorarioLlegada = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        txtCapacidad = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        txtIdOrigen = new javax.swing.JComboBox<>();
        txtIdDestino = new javax.swing.JComboBox<>();
        txtFecha = new javax.swing.JFormattedTextField();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Origen:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 118, -1, -1));

        txtNumVuelo.setText("Ingrese");
        txtNumVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumVueloActionPerformed(evt);
            }
        });
        jPanel1.add(txtNumVuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 68, -1, -1));

        jLabel2.setText("N. Vuelo:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 71, -1, -1));

        jLabel3.setText("Destino:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 163, -1, -1));

        jLabel4.setText("H. Salida:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 215, -1, -1));

        jLabel5.setText("H. Llegada:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 268, -1, -1));

        txtHorarioSalida.setText("Ingrese");
        jPanel1.add(txtHorarioSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 212, -1, -1));

        txtHorarioLlegada.setText("Ingrese");
        jPanel1.add(txtHorarioLlegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 265, -1, -1));

        jLabel6.setText("Fecha:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));

        jLabel7.setText("Estado:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        jLabel8.setText("Capacidad:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));

        jLabel9.setText("Precio:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 215, -1, -1));

        txtEstado.setText("Ingrese");
        jPanel1.add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 115, -1, -1));

        txtCapacidad.setText("Ingrese");
        jPanel1.add(txtCapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 160, -1, -1));

        txtPrecio.setText("Ingrese");
        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 212, -1, -1));

        jLabel11.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel11.setText("FORMULARIO");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 230, 55));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnGuardar)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnGuardar)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 314, 394, -1));

        txtIdOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        txtIdOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdOrigenActionPerformed(evt);
            }
        });
        jPanel1.add(txtIdOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        txtIdDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        txtIdDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdDestinoActionPerformed(evt);
            }
        });
        jPanel1.add(txtIdDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        txtFecha.setText("yyyy-mm-dd");
        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });
        jPanel1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
      String sql;
        boolean esEdicion = (idVueloSeleccionado != 0); // Si es diferente de 0 significa que estamos modificando

        if (esEdicion) {
            sql = "UPDATE vuelo SET numVuelo=?, id_origen=?, id_destino=?, horarioSalida=?, horarioLlegada=?, fecha=?, estado=?, capacidadTotal=?, precioBoleto=? WHERE id_vuelo=?";
        } else {
            sql = "INSERT INTO vuelo (numVuelo, id_origen, id_destino, horarioSalida, horarioLlegada, fecha, estado, capacidadTotal, precioBoleto) VALUES (?,?,?,?,?,?,?,?,?)";
        }

        try (Connection con = ConexionBD.getConnection(); 
             PreparedStatement pst = con.prepareStatement(sql)) {

            String fecha = txtFecha.getText();
            String hSalidaTexto = txtHorarioSalida.getText();
            String horarioSalida = hSalidaTexto.length() > 10 ? hSalidaTexto : fecha + " " + hSalidaTexto;

            String hLlegadaTexto = txtHorarioLlegada.getText();
            String horarioLlegada = hLlegadaTexto.length() > 10 ? hLlegadaTexto : fecha + " " + hLlegadaTexto;

            pst.setString(1, txtNumVuelo.getText());
            
            int indiceOrigen = txtIdOrigen.getSelectedIndex();
            if (indiceOrigen != -1) {
                pst.setInt(2, listaIdsCiudades.get(indiceOrigen));
            }

            int indiceDestino = txtIdDestino.getSelectedIndex();
            if (indiceDestino != -1) {
                pst.setInt(3, listaIdsCiudades.get(indiceDestino));
            }
            
            pst.setString(4, horarioSalida);
            pst.setString(5, horarioLlegada);
            pst.setString(6, fecha);
            pst.setString(7, txtEstado.getText());
            pst.setInt(8, Integer.parseInt(txtCapacidad.getText()));
            pst.setDouble(9, Double.parseDouble(txtPrecio.getText()));

            // Si estamos modificando entonces el  ID de vuelo tiene que cambiar
            if (esEdicion) {
                pst.setInt(10, idVueloSeleccionado);
            }

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, esEdicion ? "Vuelo actualizado correctamente" : "Vuelo registrado correctamente");
            this.dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al guardar: " + e.getMessage());
        }
        }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtNumVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumVueloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumVueloActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtIdDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdDestinoActionPerformed

    private void txtIdOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdOrigenActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioParaVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioParaVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioParaVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioParaVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioParaVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormularioParaVuelos form = new FormularioParaVuelos();
                form.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtCapacidad;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JFormattedTextField txtFecha;
    private javax.swing.JTextField txtHorarioLlegada;
    private javax.swing.JTextField txtHorarioSalida;
    private javax.swing.JComboBox<String> txtIdDestino;
    private javax.swing.JComboBox<String> txtIdOrigen;
    private javax.swing.JTextField txtNumVuelo;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
