
package proyectofinal.navegacion;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyectofinal.ConexionBD;
import proyectofinal.Vuelo;


public class SeleccionViajePasajero extends javax.swing.JFrame {
    
    private String nombreUsuario;
    private int idUsuario;
    private boolean timerActivo = true;
    public SeleccionViajePasajero(String nombreUsuario, int idUsuario) {
        initComponents();
        this.nombreUsuario = nombreUsuario;
        this.idUsuario = idUsuario;
        this.setLocationRelativeTo(null);
        cargarVuelos();

            Runnable procesoTimer = new Runnable() {
                @Override
                public void run() {
                    int tiempoActual = 30; //Prueba 1o seg, 600 para los 10 min. CAMBIARLO LUEGO!!
                    while (tiempoActual >= 0 && timerActivo) { 
                        try {
                            int minutos = tiempoActual / 60;
                            int segundos = tiempoActual % 60;
                            String tiempoFormateado = String.format("%02d:%02d", minutos, segundos);

                            // Actualiza el jlblTiempo en tiempo real que va bajando el tempotizador
                            jlblTiempo.setText("Tiempo restante: " + tiempoFormateado);

                            if (tiempoActual == 0) {
                                JOptionPane.showMessageDialog(null, "Tu sesion ha expirado, intentalo nuevo.");
                                // Se sale y devuelve  al inicio de sesion
                                new proyectofinal.InicioSesion().setVisible(true); 
                                dispose(); 
                                break; 
                            }

                            tiempoActual--; 
                            Thread.sleep(1000); 

                        } catch (InterruptedException e) {
                            break;
                        }
                    }
                }
            };

            Thread hiloCompra = new Thread(procesoTimer);
            hiloCompra.start();

        }
        
    private void cargarVuelos() {
        DefaultTableModel modelo = (DefaultTableModel) tablaViajes.getModel();
        modelo.setRowCount(0);
        
        String sql = "SELECT v.id_vuelo, c1.nombre AS origen, c2.nombre AS destino, v.numVuelo, v.horarioSalida, v.horarioLlegada, v.precioBoleto " +
                     "FROM vuelo v " +
                     "JOIN ciudad c1 ON v.id_origen = c1.id_ciudad " +
                     "JOIN ciudad c2 ON v.id_destino = c2.id_ciudad";
                     
        try (Connection con = ConexionBD.getConnection();
             Statement st = con.createStatement();
             ResultSet rs = st.executeQuery(sql)) {
             
             while (rs.next()) {
                 modelo.addRow(new Object[]{
                     rs.getInt("id_vuelo"),
                     rs.getString("origen"),
                     rs.getString("destino"),
                     rs.getString("numVuelo"),
                     rs.getString("horarioSalida"),
                     rs.getString("horarioLlegada"),
                     rs.getDouble("precioBoleto")
                 });
             }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar vuelos: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSiguiente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaViajes = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jlblTiempo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(217, 183, 240));

        btnSiguiente.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        tablaViajes.setBackground(new java.awt.Color(227, 227, 227));
        tablaViajes.setFont(new java.awt.Font("Corbel Light", 0, 12)); // NOI18N
        tablaViajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID ", "Ida", "Regreso", "No. de Vuelo", "Hora Salida", "Hora llegada", "Precio"
            }
        ));
        jScrollPane1.setViewportView(tablaViajes);

        jTextField1.setFont(new java.awt.Font("Corbel", 1, 36)); // NOI18N
        jTextField1.setText("Vuelos disponibles");

        jlblTiempo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlblTiempo.setText("Tiempo");
        jlblTiempo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(btnSiguiente)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jlblTiempo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jlblTiempo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSiguiente)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
    int fila = tablaViajes.getSelectedRow();
        if (fila != -1) {
            int idVuelo = (int) tablaViajes.getValueAt(fila, 0);
            String origen = tablaViajes.getValueAt(fila, 1).toString();
            String destino = tablaViajes.getValueAt(fila, 2).toString();
            String num = tablaViajes.getValueAt(fila, 3).toString();
            String sal = tablaViajes.getValueAt(fila, 4).toString();
            String lleg = tablaViajes.getValueAt(fila, 5).toString();
            double precio = Double.parseDouble(tablaViajes.getValueAt(fila, 6).toString());

            Vuelo vueloElegido = new Vuelo(idVuelo, origen, destino, num, sal, lleg, precio);

            // APAGAMOS EL TIMER PORQUE YA ELIGIO UN VUELO
            timerActivo = false; 

           
            PaginaPrincipalUsuario ventanaAsientos = new PaginaPrincipalUsuario(nombreUsuario, vueloElegido, idUsuario);
            ventanaAsientos.setVisible(true);
            this.dispose();

        } else {
            JOptionPane.showMessageDialog(this, "Selecciona un vuelo de la tabla para continuar.");
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel jlblTiempo;
    private javax.swing.JTable tablaViajes;
    // End of variables declaration//GEN-END:variables
}
